// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgVsAI5dNbOwdkMcWAerhRzXeGeH7ojJE',
    appId: '1:1041835508819:web:caeaaaa1bc34897c64b2a6',
    messagingSenderId: '1041835508819',
    projectId: 'presso-3a169',
    authDomain: 'presso-3a169.firebaseapp.com',
    storageBucket: 'presso-3a169.firebasestorage.app',
    measurementId: 'G-95KJZ2FZG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlCFdU4j_GRx1NXLZM_vWzwZT4kk6pICs',
    appId: '1:1041835508819:android:3accbbb32f43f64264b2a6',
    messagingSenderId: '1041835508819',
    projectId: 'presso-3a169',
    storageBucket: 'presso-3a169.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtM5boo6vL3e8qcNMimHI_fwqXxrE0-Ro',
    appId: '1:1041835508819:ios:e87dbaf5ca153bde64b2a6',
    messagingSenderId: '1041835508819',
    projectId: 'presso-3a169',
    storageBucket: 'presso-3a169.firebasestorage.app',
    iosBundleId: 'com.presso.pressoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtM5boo6vL3e8qcNMimHI_fwqXxrE0-Ro',
    appId: '1:1041835508819:ios:e87dbaf5ca153bde64b2a6',
    messagingSenderId: '1041835508819',
    projectId: 'presso-3a169',
    storageBucket: 'presso-3a169.firebasestorage.app',
    iosBundleId: 'com.presso.pressoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgVsAI5dNbOwdkMcWAerhRzXeGeH7ojJE',
    appId: '1:1041835508819:web:d9e35187107c709364b2a6',
    messagingSenderId: '1041835508819',
    projectId: 'presso-3a169',
    authDomain: 'presso-3a169.firebaseapp.com',
    storageBucket: 'presso-3a169.firebasestorage.app',
    measurementId: 'G-58Z0ZG1757',
  );
}
